name: Publish.Pypi
on:
  release:
    types:
      - created
      - edited
      - published
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine asciidoc
      - name: Convert README
        run: asciidoc -b docbook README.adoc
      - uses: docker://pandoc/core
        with:
          args: "-f docbook README.xml -t markdown_strict -o README.md"
      - name: Get VERSION
        run: echo ${{ env.GITHUB_REF }} > VERSION
      - name: Build
        run: python -m build
      - name: Publish
        run: twine upload dist/*
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
