name: Publish.Pypi
on:
  release:
    types:
      - published
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine
      - name: Get VERSION
        id: GetVersion
        uses: WyriHaximus/github-action-get-previous-tag@v1
      - run: echo ${{ steps.GetVersion.outputs.tag }} > VERSION
      - name: Build
        run: python -m build
      - name: Publish
        run: twine upload dist/*
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
