name: Run
on:
  push:
    paths-ignore:
      - "**/README.adoc"
jobs:
  Windows:
    runs-on: windows-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Download datasets
        run: |
          curl -OL https://github.com/liurui39660/Isconna/raw/master/data/data.zip
      - name: Extract datasets
        run: |
          mkdir data && tar -xf data.zip -C data
      - name: Run
        run: |
          python example/Demo.py
        env:
          PYTHONPATH: .
  Linux:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Download datasets
        run: |
          curl -OL https://github.com/liurui39660/Isconna/raw/master/data/data.zip
      - name: Extract datasets
        run: |
          unzip data.zip -d data
      - name: Run
        run: |
          python example/Demo.py
        env:
          PYTHONPATH: .
  macOS:
    runs-on: macos-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Download datasets
        run: |
          curl -OL https://github.com/liurui39660/Isconna/raw/master/data/data.zip
      - name: Extract datasets
        run: |
          unzip data.zip -d data
      - name: Run
        run: |
          python example/Demo.py
        env:
          PYTHONPATH: .
