name: Test.Demo
on:
  push:
    paths-ignore:
      - "**/README.adoc"
jobs:
  main:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        python: [3.6, 3.7, 3.8, 3.10]
    name: Python ${{ matrix.python }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Download datasets
        run: |
          curl -OL https://github.com/liurui39660/Isconna/raw/master/data/data.zip
      - name: Extract datasets (Windows)
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          mkdir data && tar -xf data.zip -C data
      - name: Extract datasets (Linux & macOS)
        if: ${{ matrix.os != 'windows-latest' }}
        run: |
          unzip data.zip -d data
      - name: Run
        run: |
          python example/Demo.py
        env:
          PYTHONPATH: .
