name: Test.Demo
on:
  push:
    paths-ignore:
      - "**/README.adoc"
jobs:
  main:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Download datasets
        run: curl -OL https://github.com/liurui39660/Isconna/raw/master/data/data.zip
      - name: Extract datasets
        run: 7z x data.zip -odata
      - name: Run
        run: python example/Demo.py
        env:
          PYTHONPATH: src
